
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wsw_demo
    username: root
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379



logging:
  level:
    com.example: debug
  pattern:
    dateformat: HH:mm:ss

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

wsw:
  jwt:
    user-secret-key: burtry
    user-token-name: token
    user-ttl: 7200000 #token有效期两小时
  alioss:
    endpoint: "oss-cn-beijing.aliyuncs.com"
    bucket-name: "wsw-demo"
