
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wsw_demo
    username: root
    password: 123456

  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - localhost:26379
          - localhost:26380
          - localhost:26381
      password: 123456
  rabbitmq:
    host: 192.168.50.128
    port: 5672
    username: guest
    password: 123456
    virtual-host: /
    listener:
      simple:
        prefetch: 1 #每次获取一条消息



logging:
  level:
    com.example: debug
  pattern:
    dateformat: HH:mm:ss

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

wsw:
  jwt:
    user-secret-key: burtry
    user-token-name: token
    user-ttl: 7200000 #token有效期两小时
  alioss:
    endpoint: "oss-cn-beijing.aliyuncs.com"
    bucket-name: "wsw-demo"

  es-demo:
    HOST: 192.168.50.128:9200
